[package]
name = "dolomann-edge-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
queues = "1.1.0"
redis = {version ="0.27.6", features = [""]}
